CREATE USER 'admin'@'%' IDENTIFIED BY 'JotyAdmin';
GRANT ALL PRIVILEGES ON *.* TO 'Admin'@'%'  WITH GRANT OPTION;
CREATE USER 'user1'@'%' IDENTIFIED BY 'JotyUser1' ;
CREATE USER 'user2'@'%' IDENTIFIED BY 'JotyUser2' ;
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON odontiordb.* TO user1;
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON odontiordb.* TO user2;
